pipeline {
    agent any
    environment {
        POSTMAN_API_KEY = credentials('POSTMAN_API_KEY')  // Securely stored Postman API key
        DISABLE_GPU = 'true'  // Optional environment variable, can be used to disable GPU if needed
    }
    tools {
        nodejs "NodeJS_Latest"  // Node.js tool configured in Jenkins
    }
    stages {
        stage('Clone GitHub Repository') {
            steps {
                echo 'Cloning SwaggerAPI repository from GitHub...'
                git url: 'https://github.com/silumi95/SwaggerAPI.git', branch: 'main'
            }
        }
        stage('Install Postman CLI') {
            steps {
                echo 'Installing Postman CLI...'
                powershell '''
                    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
                    iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))
                '''
            }
        }
        stage('Postman CLI Login') {
            steps {
                echo 'Logging into Postman CLI...'
                powershell 'postman login --with-api-key $POSTMAN_API_KEY'
            }
        }
        stage('Run Postman Collection') {
            steps {
                echo 'Running Postman collection from GitHub repository...'
                powershell '''
                    postman collection run .\\SwaggerPetstore.postman_collection.json `
                    --reporters cli,junit `
                    --reporter-junit-export .\\results.xml
                '''
            }
        }
        stage('Publish Test Results') {
            steps {
                echo 'Publishing JUnit test results...'
                junit '**/results.xml'  // Publish the results from the `results.xml` generated by Postman
            }
        }
    }
    post {
        always {
            echo 'Archiving all files for debugging...'
            archiveArtifacts artifacts: '**/*', allowEmptyArchive: true // Archive all workspace files for inspection
        }
        success {
            echo 'Postman tests completed successfully!'
        }
        failure {
            echo 'Postman tests failed!'
        }
    }
}
